// =============================================================================
// FILE: AssameseKeyboard.App/ViewModels/SettingsViewModel.cs
// INSTRUCTION: Add to the "ViewModels" folder in AssameseKeyboard.App.
//   Requires NuGet: CommunityToolkit.Mvvm 8.2.2
//   The [ObservableProperty] source generator creates the backing field
//   and the public property automatically at compile time.
// =============================================================================

using AssameseKeyboard.App.Services;
using AssameseKeyboard.Core.Mapping;
using AssameseKeyboard.Core.Services;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.Extensions.Logging;
using System;
using System.Reflection;

namespace AssameseKeyboard.App.ViewModels;

/// <summary>
/// ViewModel for the Settings page.
/// Exposes toggles for keyboard enable/disable, Windows startup,
/// and informational properties about the loaded layout.
/// </summary>
public sealed partial class SettingsViewModel : BaseViewModel
{
    // ── Dependencies ──────────────────────────────────────────────────────────
    private readonly KeyboardEngineService _engine;
    private readonly StartupService _startup;
    private readonly KeyMapper _mapper;
    private readonly ILogger<SettingsViewModel> _logger;

    // ── Observable properties (source-generated by CommunityToolkit.Mvvm) ────

    /// <summary>
    /// Whether Assamese input interception is currently active.
    /// Changing this calls Start() or Stop() on the engine.
    /// </summary>
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(StatusText))]
    [NotifyPropertyChangedFor(nameof(StatusGlyph))]
    private bool _isKeyboardEnabled;

    /// <summary>Whether the app is registered to run at Windows startup.</summary>
    [ObservableProperty]
    private bool _isStartupEnabled;

    /// <summary>User-visible error message. Shown when startup toggle fails.</summary>
    [ObservableProperty]
    private string _errorMessage = string.Empty;

    /// <summary>True when an error message should be shown.</summary>
    [ObservableProperty]
    private bool _hasError;

    // ── Constructor ───────────────────────────────────────────────────────────

    public SettingsViewModel(
        KeyboardEngineService engine,
        StartupService startup,
        KeyMapper mapper,
        ILogger<SettingsViewModel> logger)
    {
        _engine = engine ?? throw new ArgumentNullException(nameof(engine));
        _startup = startup ?? throw new ArgumentNullException(nameof(startup));
        _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));

        // Read initial state from services
        _isKeyboardEnabled = engine.IsRunning;
        _isStartupEnabled = startup.IsStartupEnabled;

        // Keep the toggle in sync when engine is toggled from the tray icon
        _engine.RunningStateChanged += OnEngineStateChanged;
    }

    // ── Computed / read-only properties ──────────────────────────────────────

    /// <summary>Status text shown next to the keyboard toggle.</summary>
    public string StatusText =>
        IsKeyboardEnabled
            ? "\u2022 Assamese input is active"           // • bullet
            : "\u25CB Assamese input is paused";          // ○ circle

    /// <summary>Segoe Fluent Icons glyph for the status indicator.</summary>
    public string StatusGlyph =>
        IsKeyboardEnabled ? "\uE73E" : "\uE711";          // Accept / Cancel

    /// <summary>Layout name from the loaded JSON file.</summary>
    public string LayoutName => _mapper.LayoutName ?? "Not loaded";

    /// <summary>Layout version from the JSON file.</summary>
    public string LayoutVersion => _mapper.LayoutVersion ?? "—";

    /// <summary>Total keys mapped in the current layout.</summary>
    public string MappingCount => $"{_mapper.MappingCount} key mappings";

    /// <summary>Application assembly version shown in About section.</summary>
    public string AppVersion
        => Assembly.GetExecutingAssembly()
                   .GetName().Version?
                   .ToString(3) ?? "1.0.0";

    // ── Property change callbacks (called by source-generated setters) ────────

    /// <summary>Called automatically when IsKeyboardEnabled changes.</summary>
    partial void OnIsKeyboardEnabledChanged(bool value)
    {
        try
        {
            if (value) _engine.Start();
            else _engine.Stop();
            ClearError();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to change keyboard engine state.");
            ShowError($"Failed to {(value ? "start" : "stop")} the keyboard engine: {ex.Message}");
            // Revert the toggle
            _isKeyboardEnabled = !value;
            OnPropertyChanged(nameof(IsKeyboardEnabled));
        }
    }

    /// <summary>Called automatically when IsStartupEnabled changes.</summary>
    partial void OnIsStartupEnabledChanged(bool value)
    {
        try
        {
            _startup.SetStartup(value);
            ClearError();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to update startup registry entry.");
            ShowError($"Could not update startup setting: {ex.Message}");
            // Revert the toggle
            _isStartupEnabled = !value;
            OnPropertyChanged(nameof(IsStartupEnabled));
        }
    }

    // ── Commands ──────────────────────────────────────────────────────────────

    /// <summary>
    /// Reloads the default keyboard layout from the embedded resource.
    /// Useful if the user has been experimenting with external layout files.
    /// </summary>
    [RelayCommand]
    private void ReloadLayout()
    {
        try
        {
            _mapper.LoadEmbeddedDefault();
            OnPropertyChanged(nameof(LayoutName));
            OnPropertyChanged(nameof(LayoutVersion));
            OnPropertyChanged(nameof(MappingCount));
            ClearError();
            _logger.LogInformation("Layout reloaded by user.");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to reload layout.");
            ShowError($"Reload failed: {ex.Message}");
        }
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    private void OnEngineStateChanged(object? sender, bool isRunning)
    {
        // May be raised from any thread — guard accordingly
        if (_isKeyboardEnabled != isRunning)
        {
            _isKeyboardEnabled = isRunning;
            OnPropertyChanged(nameof(IsKeyboardEnabled));
            OnPropertyChanged(nameof(StatusText));
            OnPropertyChanged(nameof(StatusGlyph));
        }
    }

    private void ShowError(string message)
    {
        ErrorMessage = message;
        HasError = true;
    }

    private void ClearError()
    {
        ErrorMessage = string.Empty;
        HasError = false;
    }

    // Unsubscribe when the ViewModel is GC'd (best effort)
    ~SettingsViewModel()
    {
        _engine.RunningStateChanged -= OnEngineStateChanged;
    }
}